### ISSUE TITLE
ECS code for clientDep question

### ISSUE THREAD

**Issue by IT-LCEC** [Unity-Technologies/multiplayer#13]
Thanks for the video and code. I was splitting the ECS sample into two separate projects; server and client. in PingDriverSystem.cs file, should this line be inside the driver list for loop? It doesn't appear to use the variable i so it would iterate the same code multiple times? 

Also, can you elaborate on the role of the DriverList as it would relate to the client-side code?

Line: clientDep = ClientDriver.ScheduleUpdate();

`
for (int i = 0; i < driverList.drivers.Length; ++i)
        {
            if (driverList.drivers[i].isServer != 0)
            {
                // Schedule a chain with driver update, a job to accept all connections and finally a job to delete all invalid connections
                serverDep = ServerDriver.ScheduleUpdate();
                var acceptJob = new DriverAcceptJob
                    {driver = ServerDriver, commandBuffer = commandBuffer};
                serverDep = acceptJob.Schedule(serverDep);
                var cleanupJob = new DriverCleanupJob
                {
                    serverConnections = serverConnectionList.connections,
                    serverConnectionEntities = serverConnectionList.entities,
                    commandBuffer = commandBuffer
                };
                serverDep = cleanupJob.Schedule(serverDep);
            }
            else
                clientDep = ClientDriver.ScheduleUpdate();
        }
`

**Comment by timj-unity** [comment]
Yes, the SceduleUpdate should be inside the loop.

The driverList is just a list signaling which drivers should exist (client driver and server driver). It does not own the drivers, it is just a way of controlling what to create from content rather than code. The system owns the drivers and there is never more than one client and one server driver. There is also never more than one of each in the driverList. 

If you add a DriverComponent with isServer = true the server driver will be created and updated, if you add a DriverComponent with isServer = false the client driver will be created an updated.

If you add multiple DriverComponents with the same value for isServer you will get an exception from the loop above, over newDriverList, and the DriverComponent will never be in the driverList since it did not add the correct SystemStateComponent

If you are making dedicated projects for client and server you do not need the list, you can just split the DriverUpdateSystem into two different systems, one for client and one for server, and have a way of controlling which one is active (and created its driver) based on which project you are running.
