### ISSUE TITLE
Connect to custom server

### ISSUE THREAD

**Issue by iamkisly** [Unity-Technologies/multiplayer#23]
Hello. I have custom server with networking based on dotnetty. How i can use this package for work with him ? Its possible ?

**Comment by zhuchun** [comment]
The only feasible way to communicate between different network frameworks is that using a common data format like JSON. So I bet you can't since this project should be designed for the modern high-performance multiplayer, while JSON or even BSON is too verbose somewhat.

**Comment by iamkisly** [comment]
I see no obstacles to implementing the protocol on a different basis. The protocol is very primitive, and does not respond to all
modern requirements of Reliable Data Protocol. I hope it will be completed to a full-fledged solution. I pampered a bit and made a ping server (http://non6.blogspot.com/2019/04/unity-networking-dotnetty.html), yes, it is clumsy and very, very simple, but it shows that this is more than possible.

**Comment by zhuchun** [comment]
Cool! Great work! 

Yes, networking is not black magic, and we can do it technically. However, I'm not sure if it's a good idea to work on two different frameworks because the whole team will need to learn both of them and minimize the differences as much as possible. Personally, I'm expecting the new headless server, Unity has made some success and keeps working on it.

**Comment by timj-unity** [comment]
Communicating with somthing not using Unity is currently not possible using this transport. It has a custom protocol and the implementation uses NativeContainers which are not available outside Unity. For communicating with external servers you can use regular dotnet sockets for now.
