### ISSUE TITLE
Latency even on localhost

### ISSUE THREAD

**Issue by Husain136** [Unity-Technologies/multiplayer#24]
Why is there always existing latency with this network transport?
The Non-ECS Ping sample gives a ping of > 15 ms,
and the ECS Ping sample gives a minimal > 30 ms.

**Comment by larus** [comment]
This is because of the update rate, when you send the packet is sent immediately. On the other end receive is called at the fixed update rate (60hz or every 16ms), the packet is processed and a reply sent, the reply is then also received at fixed update rate, so you can get up to 2x16ms or 32 ms latency if a full frame passes from the moment a packet is actually received on the wire. Usually I see the ping flip between either ~16 ms or ~32 ms, since actual "on wire" latency is 0.

**Comment by Husain136** [comment]
A simple Ping is 16ms using this new transport, while there 0ms of Ping using LiteNetLib or any other networking solution.
