### ISSUE TITLE
AndroidArchitecture does not contain a a definition for X86

### ISSUE THREAD

**Issue by Chompetto** [Unity-Technologies/multiplayer#30]
Upon importing master into Unity as a package I run into this import error:
Library\PackageCache\com.unity.burst@0.2.4-preview.48\Editor\BurstAotCompiler.cs(278,62): error CS0117: 'AndroidArchitecture' does not contain a definition for 'X86'

Unity Version:  Unity 2019.3.0a3 
    I have Window and Android build (+SDK)  installed.

Removing the if statement in question allows for a successful import.

**Comment by TomasRiker** [comment]
I had the same problem. Then I updated the Burst package to the latest version (1.0.4 in my case), and it worked. It was quite difficult to do that because the package isn't shown in the Package Manager. Open the file `Packages/manifest.json` and find the line mentioning `com.unity.burst`, change the version number to `1.0.4`. If the line doesn't exist, add it.

**Comment by Thowaah** [comment]
You can solve this problem with the package manager. The Burst compiler is included in a "bundle" package named "Entities" in the package manager. Open the package manager, then click on "Entities" and update it (it works for me with the 0.0.12-preview.33).

**Comment by timj-unity** [comment]
If it is fixed be upgrading burst it should be fixed by now since we use burst 1.2.0
