### ISSUE TITLE
Some questions about the current netcode

### ISSUE THREAD

**Issue by guerro323** [Unity-Technologies/multiplayer#33]
Hello!

I'm currently trying the new netcode, everything is currently going great, but there were time I had to modify the netcode.

1. It seems that GhostReceiveSystemGroup.GhostEntityMap is internal, why is that?
For example, if I make a FPS, I may need to set the owner of a spawned bullet, so when I serialize it to the client, I'm sending the ghostId of the owner, and then on the client, I get the entity from the received ghostId that was mapped in GhostEntityMap (which I needed to make public)

3. Would it be possible in the future to have an option to simulate the ClientSimulationSystemGroup every frame instead of a fixed time step? I could understand why a majority of person would need it to be set a fixed time step, but for some types of game (like some rhythm game) people may need to set it every frame.

4. Now, this is a question more related to how I can use RPC from other assemblies, I have multiple assemblies, but the most important ones are: 
- an assembly for the game
- an assembly the base of all my games (let's call it the 'gamebase' assembly)
- an assembly for the networking
I almost had no problem with that, but if I needed to send a RPC from the gamebase assembly, I just couldn't as I generated the RPC Collection on the assembly for the game itself.
So I made some modifications on the netcode to have some systems called RPCQueueSystem<TRpcCommand> where it get a RPCQueue, they are only valid if a RPC Collection is generated (the collection override RPCSystem<TRpcCollection>.OnCreate() and make the RPCQueueSystem<TRpcCommand> valids). So with that, I could call RPCs without accessing to the game assembly itself (if I wanted to call PlayerConnectRpc, I would do `RpcQueueSystem<PlayerConnectRpc>().GetRpcQueue().Schedule(..., ...);`

5. This is not really an important question, but why isn't it possible to have multiple serializers on an entity? I made a modified version of the netcode with this possibility, for now, I didn't saw any problems (except that the entity don't have a ghostType anymore, but a buffer of ghostType), but maybe there could be some?

6. Do you think it would be possible to make game replays/demos with this sytem? I thought of saving all snapshot data received from the server into a file and then replaying it later, but this may be a bad solution.

7. This is more of a feedback, but I personally think it would be better if there was an easy possibility to create and destroy client/server worlds instead of cleaning them every time you need to disconnect/reconnect.

Overall I find the current state of the netcode to be great!
Thanks for reading my questions!

**Comment by miketheprogrammer** [comment]
In response to # 6 - Replays may work, but you will need to make sure you have good interpolation and prediction. You will be seeing it from the server perspective which ticks at about 60fps. With latency and packet loss you wont have high enough granularity to just play the data.

**Comment by timj-unity** [comment]
1. It is internal because changing it will break the entire system. In the package version there is support for serializing an Entity field in a component as a weak reference - which should solve your problem if I understand it correctly.

2. Dynamic timestep is the new default behavior in the update netcode package. You can switch back to fixed byte creating a singleton component with a FixedClientTickRate component on it.

3. RpcCollection are no longer used in the updated netcode package, they are registered with the RpcSystem before connection which means it no longer matters which assembly they come from.

4. Hmm?

5. Mostly because we have not had a use-case for it, and I am still not quite sure what problem that solves?

6. Should be possible to do replays. We have it on our roadmap, but we have quite a few things with higher priority so it is not happening soon.

7. With the update bootstrap in the updated netcode you can delay the creation of client/server worlds and do it dynamically at runtime.
