### ISSUE TITLE
Windows build freezes on attempt to close application

### ISSUE THREAD

**Issue by Zolden** [Unity-Technologies/multiplayer#37]
So, I have this part on both server and client classes.

```
public void OnDestroy(){
    networkDriver.Dispose();
    networkConnections.Dispose();
}
```

But still when I'm trying to close the application (windows build), it freezes, and I have to close it through task manager. Happens to both, client and server.

And the reason this happens seems to be the fact that connection has been established. In other cases the issue doesn't exist.

Any tips to fix it? I'd like the application to close properly.

**Comment by asyasmi** [comment]
Hi @Zolden 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

I've tried to reproduce it on an empty project and in Ping sample we have but was unable to reproduce. If this issue is still relevant for you, please file a bug using Unity Bug reporter. 

Thanks, Anastasia
