### ISSUE TITLE
Unity.Networking.Transport  Questions

### ISSUE THREAD

**Issue by Opeth001** [Unity-Technologies/multiplayer#53]
Hello Everyone,

Im having few questions about the Unity.Networking.Transport. (Tank You in advance)
 
**1)** is it possible to Send data within the Connect Request  to let clients show their identities to server before being accepted ? (like a session key)

**2)** is it possible to Block a NetworkConnection ? (for cheaters to kick them from the current Game )

**Comment by TomasRiker** [comment]
I think the answer to both questions is "No". You would have to accept the connection first and then have the client send further data like their identity. After checking the identity, you can either proceed or disconnect.

**Comment by Opeth001** [comment]
Thanks @TomasRiker  for the answer !

1) so i should make 2 seperate lists one for verified connections and another for verification pending, this way i can ignore all messages from those pending and after a connection they have to identify them selfs by sending their sessions key in order to be transfered from a list to another. 
**( any suggestions will be highly appreciated )**

2/ i found a way to block users by their ip using Kubernetes API.

it will be much easier if Unity Add's these Features.

**Comment by TomasRiker** [comment]
Regarding banning by IP: Keep in mind that IP addresses can be shared by many people and can be dynamic ...

**Comment by Opeth001** [comment]
yeah they are banned for 24h. ^_^

**Comment by timj-unity** [comment]
1. No, you cannot send additional data with the connection request. If you want some kind of user / authentication you have to build that on top of the connection.

2. No, you would have to accept the connection and immediately close it. Although, if you do build a user  authentication system it is probably better to ban based on user rather than ip.
I don't think you can get access to the connecting ip in an easy way right now even after accepting the connection - there is a separate issue for that open here ( #56 )
