### ISSUE TITLE
Better documentation needed

### ISSUE THREAD

**Issue by Cretezy** [Unity-Technologies/multiplayer#60]
For users to seriously consider and adopt the new multiplayer stack, better documentation is needed.

Having a minimal example and ping/pong isn't enough, and the full FPSSample project is too complex.

Documentation should be written for:
- Common example use-cases (player movement, shooting)
- API documentation (what features are available? how do I use them?)
- Getting started (more than just minimal example)
- UNet transition (concepts, example migration for simple project)

The current Unity multiplayer landscape is hard to navigate as an outsider. UNet is deprecated but it's not clear that this replaces it since it is missing so much documentation and doesn't look like is being used at scale yet.

Additionally, issues and pull request should be addressed faster. Support is important for a core project like this

**Comment by ptrefall** [comment]
The dream is that this is all because they're working so hard towards Unite at the moment. That's barely a week away! As long as its in early alpha I think lack of documentation is ok, all we have is kind of a preview here of where its going. Nothing set in stone yet from what I understand, thus spending a lot of time on documentation is just going to add a lot of work that might need to be redone. We just need to be patient here.

They wrote this blog that kind of tried to cover the multiplayer landscape:
https://blogs.unity3d.com/2019/06/13/navigating-unitys-multiplayer-netcode-transition/

**Comment by Cretezy** [comment]
@ptrefall you are totally right about Unite being a week away. Hopefully this means that we'll have a beta with documentation soon!

 I had taken a look at that article, which did help explain the current networking space. Adding it to the README might be a good choice for new-comers.

**Comment by valkyrienyanko** [comment]
I understand some of the code in the minimal example, though I do hope they clean it up a bit so it doesn't look so daunting in the future. I don't know if everything in the minimal example is required or is simply optional. My suggestion is to make a built-in methods for some code snippets that will be at the top of our Update() method in Monobehaviour. Just to make it look cleaner.

**Comment by WAYNGROUP** [comment]
Hello,

Keep in mind taht it's in alpha state so will most likely change a lot. Writing documentation is time consuming and doing it for things that will be refactored is in my opinion a waste of time.
Also, at this stage they are working on the very low level part of the package so thing are bound to be daunting to setup. The abstraction will come later with the higher level APIs.

If you are interested in experimenting with the API at such a low level, I managed to make a few sample work here : https://github.com/WAYNGROUP/Unity-Networking-Experiments

And no I did not document what I changed from the unity repository for it to work, but comparing the files should be quite straight forward.

**Comment by Cretezy** [comment]
Unite came and pass and nothing. I hope they release a more detailed roadmap for usability of this package. 

I'm going to leave this issue open for the time being

**Comment by Archorin** [comment]
We was supposed to get a beta version of the NetCode this fall. I'm waiting...

@WAYNGROUP Did you just drop the netcode part of the sample project in your experiment or did you write your own implementation?

**Comment by WAYNGROUP** [comment]
Droped a copy of the netcode in my project.

**Comment by Cretezy** [comment]
Well it's over a month later and still nothing. I've been very disappointed with this, since I'm very uncertain about which multiplayer solution to use currently. I guess I'll use a third-party one since this doesn't seem like it's a high priority for Unity.

**Comment by ChanceNCounter** [comment]
Thing I'm confused about is the status of ECS physics vis-a-vis this multiplayer framework. There's clearly client and server logic, with prediction apparently built in. Does that mean I can just drop physics behavior in my game and assume it'll work?

Because I am (and have been) 100% prepared to write my own prediction system, but I'd rather use something Unity-native if it's about to be.

The netcode is the bottleneck for my current project. I'm stalled because I'm at a crossroads: replace the moving parts with an ECS-based solution, so I can take advantage of the new physics engine, and achieve great performance. Or, stick with PhysX and a fully OO project, so that I can make use of multiple physics scenes while I'm writing my own netcode from the ground up.

DOTS doesn't seem to support multiple physics simulations at the moment, so, even though it should be production-ready long before I'm finished, it's a non-starter... except that a forum post indicated it's a solved problem in the netcode.

*Where*? Better docs urgently needed. The existing docs gloss over all this stuff, and they've fallen into a classic trap: the docs would be an excellent *reminder* of how everything worked, if I already knew how everything worked.

I can't be spending 8 hours dissecting a library, even alpha systems, just to do an hour of development in a sandbox project. While it's in alpha or beta, that prevents me from getting my two cents in, even though I intend to use these frameworks extensively, possibly for the rest of my career. Once they're in production, it just means that using them is a chore at best.

**Comment by asyasmi** [comment]
Hi 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

Documentation should be written for:

> Common example use-cases (player movement, shooting)
Basically, we have working samples for that, but I'll add that as a note to be more elaborated. 

> API documentation (what features are available? how do I use them?)
Changelog usually contains the list, and we try to cover new features in samples, but, also, we need to make sure you have it relevantly described. 

> Getting started (more than just minimal example)
That is a good point. I guess, talks on last Unite and DOTS-shooted might help as s guidance project, but I strongly agree we need more bonds to how-to, not only existing projects. 

> UNet transition (concepts, example migration for simple project)
This is a tougher question. Since the area is still in development, it's hard to give the one and only working way for this transition without the need to create it once again on every package release. We'll be able to give a clear answer on this by the moment it'd be done if it'd be possible. 


I've added points from this thread to the review list, so closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia

**Comment by Cretezy** [comment]
Samples shouldn't be considered documentation. They don't explain the why
things are, and don't explain adding multiplayer to existing projects in
steps.

Because of the lack of this and more issues (unclear DOTS docs, etc), I've
decided to move on to Godot. Hopefully this feedback can help you keep
developers happy on your platform

**Comment by webbertakken** [comment]
I am confused as to why this issue is being closed. Is there a link to this review list or will this effectively move communication away from the public?

For a project as highly anticipated as this, I don't think it will be helpful to just close the issue and leave no trace as to how the issue would be solved. Hopefully there will be at least basic documentation to start with, long before this comes out of the experimental phase.

**Comment by ChanceNCounter** [comment]
> Samples shouldn't be considered documentation.

Emphatic +1! A code sample is always clear to the people who've spent their recent lives inside the codebase. It's definitely clear to the people who *wrote* the codebase. It's not very useful for anyone else.

We all design systems for a living. If the system you're designing is for downstream consumption, you've gotta be documenting as you go. Inline would be fine. Prose would be better. What use is a library we can't use because nobody quite understands it?

**Comment by asyasmi** [comment]
Hi to all again, 

Probably I've formulated myself incorrectly. Of course, documentation, tutorials, and samples are completely different ways of delivering information and clarification functioning of the system. We're still in the development process thought and that's why samples are the easiest to deliver and update source by far. But we never lost a need for documentation out the focus point. Personally, I don't confirm a product in a delivered state without giving an overall understanding of its usage. 
Currently, we publish packages with documentation covering features we're adding in package release https://docs.unity3d.com/Packages/com.unity.netcode@0.0/manual/index.html. It doesn't cover all of the requested points of yours and that's to be fixed. 

> For a project as highly anticipated as this, I don't think it will be helpful to just close the issue and leave no trace as to how the issue would be solved.

I've moved all issues listed here to our internal boards, unfortunately, I cannot give links to it. But I'll keep this thread updated, as well as insist on updates about documentation on the [forum](https://forum.unity.com/threads/dots-multiplayer-discussion.694669 ) also, where you can get an immediate and direct response. 


In any case, I'm gathering feedback and understand that the current solution is being built longer than all of us expected and it leads developers to look for other paths of implementation. 
Cleaning up issues here is part of the process for us also to be able to have up-to-date communication with developers and not losing any feedback, so I've closed the issue because, as you might have noticed, we rarely update this repository and thus issues like this are sitting in for long, the feedback resources are narrowed to forums and bugs (Fogbugz/Issue tracker). 

I hope I cleaned it up at least a bit, but do not hesitate to contact me if you have any further questions. 
Thanks, Anastasia
