### ISSUE TITLE
Asteroids uses PredictingTick instead of ServerTick

### ISSUE THREAD

**Issue by Jawsarn** [Unity-Technologies/multiplayer#80]
Asteroids uses PredictingTick instead of ServerTick.

**Comment by asyasmi** [comment]
Hi @Jawsarn, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

Since the moment of posing this issue, plenty of time had passed, but I've tried to check your issue. PridictionTick is used as a part of GhostPredictinSystemGroup, as in the Androids sample we widely use prediction and ghosting to give an example of its usage. 

Closing this issue, but in case of any additional questions/issues or want to elaborate on this issue - please file a bug using Unity Bug reporter or contact us on the [forum](https://forum.unity.com/threads/dots-multiplayer-discussion.694669/page-2).
Thanks, Anastasia
