### ISSUE TITLE
Question: What platforms are you planning to support with com.unity.transport platforms?

### ISSUE THREAD

**Issue by AdamRamberg** [Unity-Technologies/multiplayer#85]
The docs currently says: 

> - Currently only supports the platforms
>   - Windows, Linux, Mac OSX, iOS and Android

What other platforms are you planning to support and target? 

Thanks for building awesome content!  ❤️

**Comment by asyasmi** [comment]
Hi @AdamRamberg, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

We should support most platforms if using the BaselibNetworkInterface, so most of the platform-dependent operations must be available since 2019.3. More info [here](https://unity.com/releases/2019-3/platforms#internal-baselib). Hope that answers your question. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
