### ISSUE TITLE
CommandData problems with trigger input & slow editor 

### ISSUE THREAD

**Issue by Jawsarn** [Unity-Technologies/multiplayer#89]
Fetches of commadData buffer will get the closest older tick (happens both when sending and when you're fetching yourself). This causes clients that are lagging and not sending input for all ticks, to make a input of key_down to be used multiple frames if used out of the box. 

My current workarounds is to also add the generated tick in the command, and remove triggers if it doesn't match the tick I'm fetching for. But...

It also seems to not get the inputs to time in a good manner either with FixedTime or not in the editor when I only have some 10 fps. The command is either not sent (non fixed time) in time or has already been computed (FixedTime).

**Comment by asyasmi** [comment]
Hi @Jawsarn, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

I've tried to reproduce this issue and am investigating it now, but since we've published a new package version with updated Tick calculation it'd be cool you can check your issues against it and check if Tick issue was fixed for you. If it still is, please post a bug using Bug reporter, so we can look closer. 

Thanks a lot for all of your inquiries here, you really help us! 
Thanks, Anastasia
