### ISSUE TITLE
Guide errors

### ISSUE THREAD

**Issue by gorkadread** [Unity-Technologies/multiplayer#9]
So, following the guide the link to the ClientBehaviour.cs is erroneous as the href points to https://github.com/Unity-Technologies/multiplayer/blob/master/com.unity.transport/Documentation/workflow-client-server.md, but the file is actually located at https://github.com/Unity-Technologies/multiplayer/blob/master/com.unity.transport/Documentation/samples/clientbehaviour.cs.md. So it's missing /samples in the url. 

Second error is in the guide where the if-statement used in ServerBehaviour.cs, line 62 contains the code 
<code>continue;</code>,
but in the actual file ServerBehaviour.cs, the if-statement contains the code <code>Assert.IsTrue(true);</code>. Not debating on why that's in the file here, but it should be consistent with the guide at least :)

**Comment by LokoGD** [comment]
Yep, had errors due to inconsistency in guide and source file.

Source of ServerBehaviour.cs had (Line57):
`if (!m_Connections[i].IsCreated)
                Assert.IsTrue(true);`

When the correct was:
`if (!m_Connections[i].IsCreated)
                continue;`

Same goes for ClientBehaviour.cs, source had (Lines35 and 62):
`if (!m_Done)
                Debug.Log("Something went wrong during connect");
            return;`
and
`m_Done = true;`

When the correct was:
`if (!Done)
                Debug.Log("Something went wrong during connect");
            return;`

and
`Done = true;`

Please, correct the guide so other users don't get the same errors.

**Comment by timj-unity** [comment]
Path has been fixed, will be in next release
