### ISSUE TITLE
GhostDefaultComponent attribute doesn't work for nested entities

### ISSUE THREAD

**Issue by Jawsarn** [Unity-Technologies/multiplayer#90]
Using CreateAdditionalEntity in conversion and adding components with GhostDefaultComponent attribute won't follow the rules of the attribute.

**Comment by asyasmi** [comment]
Hi @Jawsarn, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

Recently we've been working on rewriting CodeGen for ghosting, so I'm closing this issue as should be fixed in the upcoming versions (the one which will be public after "0.3.1-preview.4"). Now you will have to mark only the main object as Ghost and all the nested entities should be added to its list. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
