### ISSUE TITLE
LinkedEntities with same Components causes badly generated code

### ISSUE THREAD

**Issue by Jawsarn** [Unity-Technologies/multiplayer#91]
Having a Ghosts with linked entities that has the same component (and one marked as ghostfield) will cause badly generated code in the TGhostSerializer, as multiple GetComponentDataFromEntity with the same type will be used. (caused InvalidProgramException: Passing an argument of size '10032'.)

**Comment by asyasmi** [comment]
Hi @Jawsarn, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

Recently we've been working on rewriting CodeGen for ghosting, so I'm closing this issue as should be fixed in the upcoming versions (the one which will be public after "0.3.1-preview.4"). 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
